### ISSUE TITLE
Collect statistics from grass website

### ISSUE THREAD

**Issue by veroandreo** [ncsu-geoforall-lab/gis714-2024-tangible-landscape#8]
I have access to Google console and I can see website performace info, we should either ask Markus to add more people there or find a way to extract these stats every month or so: 

![Image](https://github.com/ncsu-geoforall-lab/gis714-2024-tangible-landscape/assets/20075188/7cdf39a5-599d-4ef7-a7ba-458ba7d0f77a)

**Comment by petrasovaa** [comment]
This is a wrong repo...

**Comment by chaedri** [comment]
@veroandreo I'm going to close this so it can be moved to the correct repo

**Comment by veroandreo** [comment]
> @veroandreo I'm going to close this so it can be moved to the correct repo

oh, I did not realize where I created this. Sorry for the noise! Where shall I put it? grass-website directly?

**Comment by chaedri** [comment]
I'm not sure... maybe here:
https://github.com/ncsu-geoforall-lab/nsf-pose-grass-gis
